cob_x_offset_m: 0
cob_y_offset_m: 0.1
hip_roll_swap_angle_rad: 0.05
foot_roll_gyro_p_gain: 0.4
foot_roll_gyro_d_gain: 0.4
foot_pitch_gyro_p_gain: 0.4
foot_pitch_gyro_d_gain: 0.4
foot_roll_angle_p_gain: 0.4
foot_roll_angle_d_gain: 0.4
foot_pitch_angle_p_gain: 0.4
foot_pitch_angle_d_gain: 0.4
roll_gyro_cut_off_frequency: 50
pitch_gyro_cut_off_frequency: 50
roll_angle_cut_off_frequency: 50
pitch_angle_cut_off_frequency: 50
foot_x_force_p_gain: 0.01
foot_x_force_d_gain: 0.01
foot_y_force_p_gain: 0.01
foot_y_force_d_gain: 0.01
foot_z_force_p_gain: 0.01
foot_z_force_d_gain: 0.01
foot_roll_torque_p_gain: 0.001
foot_roll_torque_d_gain: 0.001
foot_pitch_torque_p_gain: 0.001
foot_pitch_torque_d_gain: 0.00025
foot_x_force_cut_off_frequency: 30
foot_y_force_cut_off_frequency: 30
foot_z_force_cut_off_frequency: 30
foot_roll_torque_cut_off_frequency: 30
foot_pitch_torque_cut_off_frequency: 30
""